# Курс "Линейная алгебра"

## Практическое задание урока 3 по теме "Матрицы и матричные операции"

**Задание 2**

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

**Решение**

In [43]:
import numpy as np

In [44]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]


Найдем сумму матриц A и B:

In [45]:
print(f'Матрица С = A + B\n{A + B}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


Найдем произведение матриц A и B:

In [46]:
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


**Задание 3**

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [47]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица B\n{C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица B
[[ 2 -4]
 [ 1  1]]


Вычислим линейную комбинацию $3A-2B+4C$:

In [48]:
print(f'Матрица D = 3A - 2B + 4C\n{3*A - 2*B +4*C}')

Матрица D = 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


**Задание 4**

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [49]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]


In [50]:
print(f'Транспонированная матрица:\n{A.T}')

Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


Вычислим матрицу $AA^{T}$

In [51]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

Вычислим матрицу $A^{T}A$.

In [52]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

**Задание 5**

 Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [53]:
def matrix_mnoj(massiv1, massiv2):
    mi = massiv1.shape[1]
    mk = massiv2.shape[1]
    result = [[0 for k in range(mk)] for l in range(mk)]
 
    if massiv1.shape[1] == massiv2.shape[0]:
 
        for j in range(mk):
            for k in range(mk):
                znacen = 0
 
                for i in range(mi):
                    znacen += massiv1[k][i] * massiv2[i][j]
                result[k][j] = znacen
 
    else:
        print("razmernost matric ne correctna")
 
    return result

In [54]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [55]:
print(matrix_mnoj(A, B))

[[4, -11], [12, -3]]


## Практическое задание урока 4 по теме "Матрицы и матричные операции"

**Задание 1**

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [56]:
x=0.43
a = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 0.4168708  -0.90896575]
 [ 0.90896575  0.4168708 ]]
Определитель:
1


In [57]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [58]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


**Задание 2**

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
***Решение выполнено на листочке***

**Задание 3**

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [59]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]


Найдем определитель матрицы

In [60]:
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


***Определитель равен нулю, следовательно, матрица вырожденная.***

**Задание 4**

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [61]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица a:\n{a}')

Матрица a:
[[1 2 3]
 [1 1 1]
 [2 3 4]]


In [62]:
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы a: {r}')

Ранг матрицы a: 2


In [63]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица b:\n{b}')

Матрица b:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]


In [64]:
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы b: {r}')

Ранг матрицы b: 3
