# Курс "Линейная алгебра"

## Практическое задание урока 6 по теме "Системы линейных уравнений"

In [161]:
import numpy as np
import scipy
import scipy.linalg

### Задание 1

Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

**Решение**

выполнено на листочке

### Задание 2 

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

**Решение**

In [162]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print(f'Матрица A:\n{A}')

A1 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print(f'Расширенная матрица A:\n{A1}')

Матрица A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Расширенная матрица A:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]


In [163]:
r_A = np.linalg.matrix_rank(A)
print(f'Ранг матрицы A: {r_A}')

r_A1 = np.linalg.matrix_rank(A1)
print(f'Ранг расширенной матрицы A: {r_A1}')

Ранг матрицы A: 3
Ранг расширенной матрицы A: 3


Ранг $A$ равен рангу расширенной матрицы $\tilde A$, следовательно, СЛАУ имееет решение. Данные ранги совпадают с числом неизвестных в СЛАУ, следовательно, решение единственное.

In [164]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
print(f'Матрица B:\n{B}')

B1 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print(f'Расширенная матрица B:\n{B1}')

Матрица B:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Расширенная матрица B:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]


In [165]:
r_B = np.linalg.matrix_rank(B)
print(f'Ранг матрицы B: {r_B}')

r_B1 = np.linalg.matrix_rank(B1)
print(f'Ранг расширенной матрицы B: {r_B1}')

Ранг матрицы B: 1
Ранг расширенной матрицы B: 2


Ранг матрицы $B$ меньше ранга расширенной матрицы $\tilde B$. Следовательно, СЛАУ несовместна.

In [166]:
C = np.array([[1, 2, 5], [3, 1, -8]])
print(f'Матрица C:\n{C}')

C1 = C = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print(f'Расширенная матрица :\n{C1}')

Матрица C:
[[ 1  2  5]
 [ 3  1 -8]]
Расширенная матрица :
[[ 1  2  5  4]
 [ 3  1 -8 -2]]


In [167]:
r_C = np.linalg.matrix_rank(C)
print(f'Ранг матрицы C: {r_C}')

r_C1 = np.linalg.matrix_rank(C1)
print(f'Ранг расширенной матрицы C: {r_C1}')

Ранг матрицы C: 2
Ранг расширенной матрицы C: 2


Ранг $C$ равен рангу расширенной матрицы $\tilde C$, следовательно, СЛАУ имееет решение. Данные ранги меньше числа неизвестных в СЛАУ, следовательно, система имеет бесоконечное количество решений.

### Задание 3 

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

**Решение**

In [168]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
print(f'Матрица A:\n{A}')

A1 = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print(f'Расширенная матрица A:\n{A1}')

Матрица A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Расширенная матрица A:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]


In [169]:
r_A = np.linalg.matrix_rank(A)
print(f'Ранг матрицы A: {r_A}')

r_A1 = np.linalg.matrix_rank(A1)
print(f'Ранг расширенной матрицы A: {r_A1}')

Ранг матрицы A: 4
Ранг расширенной матрицы A: 4


Ранг $A$ равен рангу расширенной матрицы $\tilde A$, следовательно, СЛАУ имееет решение. Данные ранги совпадают с числом неизвестных в СЛАУ, следовательно, решение единственное.

### Задание 4

Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

**Решение**

Преобразуем расширенную матрицу к ступенчатой форме

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a
\end{matrix}
\end{pmatrix} \Rightarrow $$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 2a\\
c - 3a - 2b
\end{matrix}
\end{pmatrix}.$$


Если c - 3a - 2b $\neq$ 0 ,  то система является несовместной.

## Практическое задание урока 6 по теме "Системы линейных уравнений"

### Задание 1

Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

**Решение**

**a)**

In [170]:
A = np.array([[1, -2], [3, -4]])
print(f'Матрица A:\n{A}')
print(f'Определитель матрицы A:\n{np.linalg.det(A):.0f}')

Матрица A:
[[ 1 -2]
 [ 3 -4]]
Определитель матрицы A:
2


Найдем определители $detA_{1}$, $detA_{2}$:

In [171]:
A1 = np.array([[1, -2], [7, -4]])
print(f'Матрица A1:\n{A1}')
print(f'Определитель матрицы A1:\n{np.linalg.det(A1):.0f}')

Матрица A1:
[[ 1 -2]
 [ 7 -4]]
Определитель матрицы A1:
10


In [172]:
A2 = np.array([[1, 1], [3, 7]])
print(f'Матрица A2:\n{A2}')
print(f'Определитель матрицы A2:\n{np.linalg.det(A2):.0f}')

Матрица A2:
[[1 1]
 [3 7]]
Определитель матрицы A2:
4


Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2.$$

**б)**

In [173]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица A:\n{a}')
print(f'Определитель матрицы A:\n{np.linalg.det(a):.0f}')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель матрицы A:
43


Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

In [174]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица A1:\n{a1}')
print(f'Определитель матрицы A1:\n{np.linalg.det(a1):.0f}')

Матрица A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель матрицы A1:
86


In [175]:
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица A2:\n{a2}')
print(f'Определитель матрицы A2:\n{np.linalg.det(a2):.0f}')

Матрица A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель матрицы A2:
-43


In [176]:
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица A3:\n{a3}')
print(f'Определитель матрицы A3:\n{np.linalg.det(a3):.0f}')

Матрица A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель матрицы A3:
43


Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{2}}{detA} = \frac{43}{43}=1.$$

### Задание 2 

Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

**Решение**

выполнено на листочке

### Задание 3 

Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [177]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
print(f'Матрица a:\n{a}')

Матрица a:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]


In [178]:
P, L, U = scipy.linalg.lu(a)

print(f'Матрица P:\n{P}')
print(f'Матрица L:\n{L}')
print(f'Матрица U:\n{U}')

Матрица P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Матрица L:
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
Матрица U:
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


In [179]:
b = np.array([1, -6, -5])
b

array([ 1, -6, -5])

Решим систему $Ly=b:$

In [180]:
y = np.linalg.solve(L, b)
y

array([ 1.        , -6.81818182, -6.        ])

Решим систему $Ux=y:$

In [181]:
x = np.linalg.solve(U, y)
x

array([ 3.38461538, -3.11538462, -2.88461538])

Осуществим проверку, подставив полученные значения в исходную систему

In [182]:
np.dot(a, x)

array([-5.,  1., -6.])

### Задание 4

Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [183]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
print(f'Матрица a:\n{a}')

Матрица a:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]


In [184]:
L = np.linalg.cholesky(a)
L

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

In [185]:
b = np.array([531, -460, 193])
b

array([ 531, -460,  193])

Решим систему $Ly=b:$

In [186]:
y = np.linalg.solve(L, b)
y

array([ 59., -33., -12.])

И решим систему $L^{T}x=y:$

In [187]:
x = np.linalg.solve(L.T, y)
x

array([ 6., -5., -4.])

Осуществим проверку, подставив полученные значения в исходную систему

In [188]:
np.dot(a, x)

array([ 531., -460.,  193.])

### Задание 5 

Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [189]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица A:\n{a}')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]


In [190]:
b = np.array([10, -2, 1])
b

array([10, -2,  1])

In [191]:
def Cramer(A, B):
    m = len(A)
    det = np.linalg.det(A)
    r = []
    for i in range(m):
        VM = np.copy(A)
        VM[:,i]=B
        r.append(np.linalg.det(VM)/det)
    return r
x = Cramer(a, b)
x

[2.0000000000000018, -1.0000000000000009, 1.0]

Осуществим проверку, подставив полученные значения в исходную систему

In [192]:
np.dot(a, x)

array([10., -2.,  1.])