# Курс "Линейная алгебра"

## Дополнительное практическое задание

Дан датасет с ирисами

Задача:
- понизить ранг датасета с 4 до 3 (или 2)
- отыскать матрицу перехода из одного пространства в другое

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
# загрузка набора данных Ирисы:
iris = datasets.load_iris()
# данные
print(iris.data[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [3]:
A = iris.data

### Сингулярное разложение матрицы

In [4]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [5]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [6]:
print(f'Первые шесть строк матрицы D:\n{D[:6]}')

Первые шесть строк матрицы D:
[[95.96  0.    0.    0.  ]
 [ 0.   17.76  0.    0.  ]
 [ 0.    0.    3.46  0.  ]
 [ 0.    0.    0.    1.88]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]


In [7]:
print(f'Матрица U:\n{U}')

Матрица U:
[[-0.06  0.13  0.   ... -0.09 -0.1  -0.08]
 [-0.06  0.11  0.07 ...  0.04 -0.03  0.01]
 [-0.06  0.12  0.   ...  0.03  0.2   0.14]
 ...
 [-0.09 -0.05 -0.04 ...  0.98 -0.02 -0.01]
 [-0.09 -0.06 -0.21 ... -0.02  0.94 -0.03]
 [-0.09 -0.05 -0.1  ... -0.01 -0.03  0.97]]


In [8]:
print(f'Матрица V:\n{V}')

Матрица V:
[[-0.75  0.28  0.5   0.32]
 [-0.38  0.55 -0.68 -0.32]
 [-0.51 -0.71 -0.06 -0.48]
 [-0.17 -0.34 -0.54  0.75]]


##### Используем SVD для понижения ранга матрицы A:

In [9]:
def compress_svd(matrix, k): # Параметр k задает степень сжатия
    """
    Perform svd decomposition and truncated (using k singular values/vectors) reconstruction
    returns
    --------
      reconstructed matrix reconst_matrix, array of singular values s
    """
    
    U,s,V = np.linalg.svd(matrix,full_matrices=False)
    reconst_matrix = np.dot(U[:,:k],np.dot(np.diag(s[:k]),V[:k,:]))
    
    return reconst_matrix,s

In [10]:
A2, s2 = compress_svd(A,2)

In [11]:
print(f'Матрица с пониженным рангом:\n{A2[:10]}')

Матрица с пониженным рангом:
[[5.1  3.51 1.4  0.2 ]
 [4.75 3.2  1.46 0.26]
 [4.69 3.22 1.31 0.19]
 [4.61 3.09 1.46 0.27]
 [5.07 3.51 1.36 0.19]
 [5.53 3.73 1.68 0.29]
 [4.73 3.23 1.36 0.21]
 [5.01 3.4  1.48 0.24]
 [4.38 2.93 1.39 0.26]
 [4.81 3.23 1.49 0.26]]


In [16]:
U, s, W = np.linalg.svd(A2)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов
D2 = np.zeros_like(A2, dtype=float)
D2[np.diag_indices(min(A2.shape))] = s

In [17]:
print(f'Первые шесть строк матрицы D2:\n{D2[:6]}')

Первые шесть строк матрицы D2:
[[95.96  0.    0.    0.  ]
 [ 0.   17.76  0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.  ]]
